						<li><a href="agriculture.php">Agriculture</a></li>
						<li><a href="anthropology.php">Anthropology and Archaeology</a></li>
						<li><a href="art.php">Art</a></li>
						<li><a href="astronomy.php">Astronomy</a></li>
						<li><a href="biology.php">Biology</a></li>
						<li><a href="business.php">Business and Management</a></li>
						<li><a href="chemistry.php">Chemistry</a></li>
						<li><a href="computer.php">Computer Science and Mathematics</a></li>
						<li><a href="earth.php">Earth and Environmental Sciences</a></li>
						<li><a href="economics.php">Economics</a></li>
						<li><a href="education.php">Education</a></li>
						<li><a href="engineering.php">Engineering and Technology</a></li>
						<li><a href="food.php">Food and Home Economics</a></li>
						<li><a href="history.php">History</a></li>
						<li><a href="humanities.php">Humanities and Library Science</a></li>
						<li><a href="language.php">Language and Literature</a></li>
						<li><a href="law.php">Law</a></li>
						<li><a href="medicine.php">Medicine</a></li>
						<li><a href="military.php">Military Science</a></li>
						<li><a href="music.php">Music</a></li>
						<li><a href="philosophy.php">Philosophy</a></li>
						<li><a href="photography.php">Photography</a></li>
						<li><a href="physics.php">Physics</a></li>
						<li><a href="political.php">Political Science</a></li>
						<li><a href="psychology.php">Psychology</a></li>
						<li><a href="recreation.php">Recreation and Leisure</a></li>
						<li><a href="religion.php">Religion</a></li>
						<li><a href="science.php">Science and Technology</a></li>
						<li><a href="social.php">Social Sciences</a></li>